version: "3.8"

services: # <-- Add this!
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ccdn0koment
      POSTGRES_DB: KepegServerDB
    ports:
      - "5432:5432"

  server:
    build: .
    container_name: kepeg-server
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
      - "5555:5555"
